{{ if not .Values.configApplication }}

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-ingress-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    {{- include "aks-baseline.labels" . | nindent 4 }}
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  sources:
    - repoURL: https://traefik.github.io/charts
      chart: traefik
      targetRevision: 41.2.0
      helm:
        valuesObject:
          ingressClass:
            name: traefik
          ports:
            web:
              http:
                redirections:
                  entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true
          service:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz

{{ end }}
