baseDomain: ""

azure:
  subscriptionID: ""

apps:
  certManager:
    letsencryptContactEmail: ""
  externalDNS:
    azure:
      # For WorkloadIdentityFederation auth.
      # The referred client must have a federated credential for system:serviceaccount:external-dns:external-dns
      workloadIdentityClientID: ""
      dnsZoneResourceGroup: ""
