---
replicaCount: 1
# Options
# - red
# - green
# - blue
color: blue

image:
  repository: argoproj/rollouts-demo
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""  # If empty, uses cluster default
  annotations: {}
  host: ""
  tls:
    enabled: true
    secretName: ""

resources:
  requests:
    memory: 32Mi
    cpu: 5m
