---
replicaCount: 1

image:
  repository: argoproj/rollouts-demo
  tag: blue
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: {}
  host: ""
  tls:
    enabled: true
    secretName: colors-tls

resources:
  requests:
    memory: 32Mi
    cpu: 5m
